dist: trusty
sudo: required
services:
- docker
env:
  matrix:
  - COREOS_TRACK=stable
  - COREOS_TRACK=beta
  - COREOS_TRACK=alpha
before_script:
- curl https://${COREOS_TRACK}.release.core-os.net/amd64-usr/current/version.txt -o version.txt
- export $(cat version.txt | xargs)
- curl https://${COREOS_TRACK}.release.core-os.net/amd64-usr/${COREOS_VERSION}/coreos_production_image_packages.txt -o packages.txt
- export DOCKER_VERSION="$(cat packages.txt | grep -P 'app-emulation\/docker-([0-9]{2}.[0-9]{2}.[0-9]{1,2})' -o | cut -d '-' -f 3)"
- export RUNC_COMMIT="$(docker run --rm -it docker:$DOCKER_VERSION docker-runc -v | grep commit | cut -d ' ' -f 2)"
script:
- wget https://github.com/NVIDIA/nvidia-container-runtime/archive/master.zip
- unzip master.zip
- cd nvidia-container-runtime-master
- docker build --build-arg RUNC_COMMIT="${RUNC_COMMIT}" --build-arg PKG_VERS="x" --build-arg PKG_REV="1" -t trevex/nvidia-container-runtime -f Dockerfile.centos7 .
- mkdir -p output
- docker run --rm -i -v ${PWD}/output:/output trevex/nvidia-container-runtime cp -R /tmp/nvidia-container-runtime-x/SOURCES /output
- cd output
- export $ARTIFACT_FILE=nvidia-container-runtime-$COREOS_TRACK-$COREOS_VERSION.zip
- zip -r ../../$ARTIFACT_FILE .
before_deploy:
  - git config --local user.name "Niklas Voss"
  - git config --local user.email "niklas.voss@gmail.com"
  - git tag "${RUNC_COMMIT}"
deploy:
  provider: releases
  api_key:
    secure: AhBkruTdeYSkr6t2CvTkPfy49zVTEPK5dMmIssnZhnoQ40siNMbHEN09jWYyBbDORptv6RuO7WaXu+rSnpY28ysKOJKSMmk5BvOvAh5AyuPe2HiySM4EbtLWCl+5P9IzxODAXPIIfdGeyPR+QV1KY6tYPiF72i0LOAyzShPo1m+vYR0n1NIgA/ouY1GOAsJRRFZPCbt55YEiRQDHXaF07IZHb87VneYLdGCwrMO0i3NgaUQ2TQlz+J5jOIdnIYltq1ooPVv0CtHITmCyBKpcIB83gdxoqOO0iIn/n0JxKFOZcv6kPGeB0jEBeyePVoHXw9P93BWj6nzm7n7B4cY8v5XuyM6oeR/RdomXMFJFxoy5wOM/5YMg6Ii9mYEZ5gTGqkOtW92+HJ4gOgxPW1tVqYo/CqQXZro9IMktw/M22uT1EYD+dI8m5glbYk0hpxFUrKOW8+DaUNBUM7KQtMNKmniHgmanCzKZYJxQt/dujqPPBmMmBcXT9cVfJVrnPZpfLb4wVYCUC/3OdBlhf/uFm5BnzOcQf+X8V1ygfAd5eHgQbPnvEx68oHcMLfqOfBHFgI1hk1C+Zj8p0YnqvOWEpLyO4h0MR3EKYnUkLIMP+lh4YBZV9ifVS/x/mL7rTO51vxUvPHWwzeMYiHDAVdyEhhX/9YkbgMQhJj5zkKPOB9U=
  file: "${ARTIFACT_FILE}"
  skip_cleanup: true
  on:
    repo: trevex/coreos-nvidia-container-runtime
